WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/99d6bda0-f40f-4184-91d0-30f4da0aa7ae